# Generated by Django 5.2.14 on 2026-06-02 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('subject', models.CharField(max_length=998)),
                ('body', models.TextField(help_text="Plain-text body. Django template syntax is supported; the rendering context contains 'applicant' plus any extra context passed by the caller.")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('out', 'Outbound'), ('in', 'Inbound')], max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('received', 'Received')], default='pending', max_length=10)),
                ('from_address', models.EmailField(max_length=254)),
                ('to_address', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=998)),
                ('body', models.TextField()),
                ('message_id', models.CharField(blank=True, db_index=True, help_text='RFC 5322 Message-ID of the message (without angle brackets).', max_length=998)),
                ('in_reply_to', models.CharField(blank=True, help_text='Message-ID of the message this is a reply to, if any.', max_length=998)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('raw', models.TextField(blank=True, help_text='Raw RFC 5322 source (inbound only, optional).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_messages', to='applicants.applicant')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='mailroom.mailtemplate')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['direction', 'status'], name='mailroom_ma_directi_6311e6_idx'), models.Index(fields=['applicant', '-created_at'], name='mailroom_ma_applica_3b7a19_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('message_id__gt', '')), fields=('direction', 'message_id'), name='mailroom_mailmessage_unique_direction_msgid')],
            },
        ),
    ]
